#index:
#    path: /
#    controller: App\Controller\DefaultController::index



# the "app_lucky_number" route name is not important yet

index_motd:
  path: /
  controller: App\Controller\IndexController::motd


blog_page:
  path: /blog
  controller: App\Controller\BlogController::blogPage


blog_show:
  path: /blog/post/{id}
  controller: App\Controller\BlogPostController::show


app_lucky_number:
  path: /lucky
  controller: App\Controller\LuckyController::number

