#index:
#    path: /
#    controller: App\Controller\DefaultController::index



# the "app_lucky_number" route name is not important yet

index_motd:
  path: /
  controller: App\Controller\IndexController::motd


blog_page:
  path: /blog
  controller: App\Controller\BlogController::blogPage


blogs_with_category:
  path: /blogs/{id}
  controller: App\Controller\BlogController::blogsWithCategory

blog_show:
  path: /blog/post/{id}
  controller: App\Controller\BlogPostController::show


dashboard:
    path: /dashboard
    controller: App\Controller\DashboardController::dashboard

dashboard_category_blog:
  path: /dashboard/category/blog/{id}
  controller: App\Controller\DashboardBlogController::dashBlogsWithcategory

dashboard_blog_show:
  path: /dashboard/category/blog/post/{id}
  controller: App\Controller\DashboardBlogController::show

dashboard_blog_edit:
  path: /dashboard/category/blog/post/edit/{id}
  controller: App\Controller\DashboardBlogController::editBlog

dashboard_blog_delete:
  path: /dashboard/category/blog/post/delete/{id}
  controller: App\Controller\DashboardBlogController::deleteBlogpost

dashboard_blog_image_upload:
  path: /dashboard/category/blog/post/edit/upload/{id}
  controller: App\Controller\DashboardImageUploadController::uploadImage

dashboard_create_blog_post:
  path: /dashboard/createblogpost
  controller: App\Controller\DashboardBlogController::createBlogPost

dashboard_create_blog_post_save:
  path: /dashboard/createblogpost/save
  controller: App\Controller\DashboardBlogController::createBlogPostSaveButton

dashboard_blog_edit_save:
  path: /dashboard/category/blog/post/edit/save/{id}
  controller: App\Controller\DashboardBlogController::editSaveButton

app_lucky_number:
  path: /lucky
  controller: App\Controller\LuckyController::number

