#index:
#    path: /
#    controller: App\Controller\DefaultController::index



# the "app_lucky_number" route name is not important yet

#index_motd:
#  path: /
#  controller: App\Controller\IndexController::motd


#-----------------BLOG and BLOGS-------------------------------------------------------
blog_page:
  path: /
  controller: App\Controller\BlogController::blogPage


blogs_search:
  path: /blogs/search
  controller: App\Controller\BlogController::search

blogs_with_category:
  path: /blogs/{id}
  controller: App\Controller\BlogController::blogsWithCategory

blog_show:
  path: /blog/{id}
  controller: App\Controller\BlogPostController::show






#-----------------DASHBOARD-------------------------------------------------------
dashboard:
    path: /dashboard
    controller: App\Controller\DashboardController::dashboard

dashboard_category:
    path: /dashboard/category/
    controller: App\Controller\DashboardCategoryController::category

dashboard_createCategory:
  path: /dashboard/category/create
  controller: App\Controller\DashboardCategoryController::createCategory

dashboard_create_category_save:
  path: /dashboard/category/create/save
  controller: App\Controller\DashboardCategoryController::categorySaveButton

dashboard_edit_category:
  path: /dashboard/category/edit/{id}
  controller: App\Controller\DashboardCategoryController::editCategory

dashboard_edit_category_save:
  path: /dashboard/category/edit/save/{id}
  controller: App\Controller\DashboardCategoryController::editSaveButton

dashboard_delete_category:
  path: /dashboard/category/delete/{id}
  controller: App\Controller\DashboardCategoryController::deleteCategoryButton


dashboard_category_blog:
  path: /dashboard/category/blog/{id}
  controller: App\Controller\DashboardBlogController::dashBlogsWithcategory




#-----------------DASHBOARD BLOGS-------------------
dashboard_blog_show:
  path: /dashboard/category/blog/post/{id}
  controller: App\Controller\DashboardBlogController::show


dashboard_blog_edit:
  path: /dashboard/category/blog/post/edit/{id}
  controller: App\Controller\DashboardBlogController::editBlog

dashboard_blog_delete:
  path: /dashboard/category/blog/post/delete/{id}
  controller: App\Controller\DashboardBlogController::deleteBlogpost


dashboard_create_blog_post:
  path: /dashboard/createblogpost
  controller: App\Controller\DashboardBlogController::createBlogPost

dashboard_create_blog_post_save:
  path: /dashboard/createblogpost/save
  controller: App\Controller\DashboardBlogController::createBlogPostSaveButton

dashboard_blog_edit_save:
  path: /dashboard/category/blog/post/edit/save/{id}
  controller: App\Controller\DashboardBlogController::editSaveButton


#-----------------IMAGE UPLOAD-------------------
dashboard_blog_image_upload:
  path: /dashboard/category/blog/post/edit/upload/{id}
  controller: App\Controller\DashboardImageUploadController::uploadImage




