#index:
#    path: /
#    controller: App\Controller\DefaultController::index



# the "app_lucky_number" route name is not important yet

index_motd:
  path: /
  controller: App\Controller\IndexController::motd


blog_page:
  path: /blog
  controller: App\Controller\BlogController::blogPage


blogs_with_category:
  path: /blogs/{id}
  controller: App\Controller\BlogController::blogsWithCategory

blog_show:
  path: /blog/post/{id}
  controller: App\Controller\BlogPostController::show


dashboard:
    path: /dashboard
    controller: App\Controller\DashboardController::dashboard

dashboard_category_blog:
  path: /dashboard/category/blog/{id}
  controller: App\Controller\DashboardBlogController::dashBlogsWithcategory

dashboard_blog_show:
  path: /dashboard/category/blog/post/{id}
  controller: App\Controller\DashboardBlogController::show

dashboard_blog_edit:
  path: /dashboard/category/blog/post/edit/{id}
  controller: App\Controller\DashboardBlogController::editBlog
dashboard_blog_edit_save:
  path: /dashboard/category/blog/post/edit/save/{id}
  controller: App\Controller\DashboardBlogController::saveButton

app_lucky_number:
  path: /lucky
  controller: App\Controller\LuckyController::number

